site:
  title: SUSE® Storage
  start_page: 1.9@storage:en:longhorn-documentation.adoc

content:
  sources:
    - url: ./
      branches: HEAD
      start_paths: [shared, docs/*]

ui:
  bundle:
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./dsc-style-bundle/supplemental-files/rancher

asciidoc:
  attributes:
    page-pagination: ''
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'

output:
  dir: build/site
