site:
  title: SUSE® Storage
  start_page: 1.7.0@storage:en:longhorn-documentation.adoc

content:
  sources:
    - url: https://github.com/rancher/longhorn-product-docs.git
      branches: [main]
      start_paths: [docs/version-1.7.0, docs/version-1.8.0]

ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./product-docs-supplemental-files

asciidoc:
  attributes:
    page-pagination: ''
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'

output:
  dir: build/site
