site:
  title: SUSE® Storage
  start_page: 1.8.0@storage:en:longhorn-documentation.adoc

content:
  sources:
    - url: https://github.com/rancher/longhorn-product-docs.git
      branches: [main]
      start_paths: [docs/version-1.7.0, docs/version-1.8.0, docs/version-1.9.0]

ui:
  bundle:
    url: https://github.com/SUSEdoc/dsc-style-bundle/blob/main/default-ui/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./dsc-style-bundle/supplemental-files/rancher

asciidoc:
  attributes:
    page-pagination: ''
  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
antora:
  extensions:
  - require: '@antora/lunr-extension'

output:
  dir: build/site
